FROM node:18-alpine

# Install n8n manually
RUN npm install -g n8n

ENV GENERIC_TIMEZONE=UTC
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=codebyviraj
ENV N8N_BASIC_AUTH_PASSWORD=virajjaat
ENV PORT=5678

EXPOSE 5678

CMD ["n8n"]
